# Site settings
title: Manuel Briot - Blog
email: briot.manuel@gmail.com
description: >
  Développeur chez Decathlon - Lille, France
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mbriot.github.io" # the base hostname & protocol for your site
twitter_username: mbriot
github_username:  mbriot

# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
lang: fr_FR
author: manuel briot
